apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ai-gateway
spec:
  gatewayClassName: agentgateway
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: unified-ai-backend
spec:
  type: AI
  ai:
    llm:
      openai:
        model: gpt-4o-mini
        authToken:
          kind: SecretRef
          secretRef:
            name: openai-secret
      # Configure how different API paths are processed using suffix matching.
      routes:
        "/v1/chat/completions": "completions"
        "/v1/messages": "messages"
        "/v1/models": "models"
        "*": "passthrough"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ai-route
spec:
  parentRefs:
  - name: ai-gateway
  rules:
  - backendRefs:
    - group: gateway.kgateway.dev
      kind: Backend
      name: unified-ai-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
stringData:
  Authorization: "Bearer sk-your-openai-key"
